#!/bin/bash

# requires twine: `pip install twine`

set -ex

python3 setup.py sdist bdist_wheel

twine check dist/*

# upload to test repo
twine upload --repository-url https://test.pypi.org/legacy/dist/* dist/*

# upload to production repo
#twine upload dist/*
