#!/bin/bash

# 1. Run all examples
# 2. Update verison number in railib/__init__.py
# 3. Tag the repo with the version number:
#   $ git tag <version>
#   $ git push origin --tags
# 4. Run ./release-build, make sure no issues
# 5. Run this script
# 6. Verify that the expected version appears on https://pypi.org

# Note, requires twine: `pip install twine`

set -ex

./release-build

./release-upload

