#!/bin/bash

set -ex

ENGINE="nhd-2021-10-19-small"

#python3 ./list_users.py
#python3 ./get_user.py <username>

# create engine (409 if already exists)
python3 ./create_engine.py $ENGINE --size=XS
python3 ./list_engines.py
python3 ./list_engines.py --state=PROVISIONED
python3 ./get_engine.py $ENGINE

#python3 ./get_database.py sdk-test
# should return a 404

# create database
python3 ./create_database.py sdk-test $ENGINE --overwrite
python3 ./list_databases.py
python3 ./get_database.py sdk-test

# show results, problems and errors
python3 ./run_query.py sdk-test $ENGINE "1+1"
python3 ./show_results.py sdk-test $ENGINE
python3 ./show_problems.py sdk-test $ENGINE
python3 ./show_errors.py

# install source
python3 ./install_source.py sdk-test $ENGINE hello.rel
python3 ./list_sources.py sdk-test $ENGINE
python3 ./get_source.py sdk-test $ENGINE hello
python3 ./list_edb.py sdk-test $ENGINE

# clone database
python3 ./clone_database.py sdk-test-clone $ENGINE sdk-test
python3 ./list_databases.py
python3 ./get_database.py sdk-test-clone
python3 ./list_sources.py sdk-test $ENGINE
python3 ./get_source.py sdk-test $ENGINE hello
python3 ./list_edb.py sdk-test $ENGINE

# delete source
python3 ./list_sources.py sdk-test $ENGINE
python3 ./delete_source.py sdk-test $ENGINE hello
python3 ./list_sources.py sdk-test $ENGINE
