#!/bin/bash

set -e

ENGINE="2021-10-29-bradlo-s"

python3 ./list_users.py

# grab first user-id from list
USERID=`python3 ./list_users.py | grep -m 1 -E "\"id\":.*,$" | sed "s/^.*\"id\":[ \t]*//" | sed "s/,$//"`
python3 ./get_user.py $USERID

python3 ./create_engine.py $ENGINE --size=XS
python3 ./list_engines.py
python3 ./list_engines.py --state=PROVISIONED
python3 ./get_engine.py $ENGINE

#python3 ./get_database.py sdk-test
# should return a 404

# create database
python3 ./create_database.py sdk-test $ENGINE --overwrite
python3 ./list_databases.py
python3 ./get_database.py sdk-test

# show results, problems and errors
python3 ./run_query.py sdk-test $ENGINE "1+1"
python3 ./show_results.py sdk-test $ENGINE
python3 ./show_problems.py sdk-test $ENGINE

# install source
python3 ./install_source.py sdk-test $ENGINE hello.rel
python3 ./list_sources.py sdk-test $ENGINE
python3 ./get_source.py sdk-test $ENGINE hello
python3 ./list_edbs.py sdk-test $ENGINE

# clone database
python3 ./clone_database.py sdk-test-clone $ENGINE sdk-test
python3 ./list_databases.py
python3 ./get_database.py sdk-test-clone
python3 ./list_sources.py sdk-test $ENGINE
python3 ./get_source.py sdk-test $ENGINE hello
python3 ./list_edbs.py sdk-test $ENGINE

# delete source
python3 ./list_sources.py sdk-test $ENGINE
python3 ./delete_source.py sdk-test $ENGINE hello
python3 ./list_sources.py sdk-test $ENGINE

# load_csv
python3 ./load_csv.py bradlo-test $ENGINE sample.csv -r sample_csv
python3 ./run_query.py bradlo-test $ENGINE sample_csv
python3 ./load_csv.py bradlo-test $ENGINE sample_no_header.csv --header-row=0 -r sample_csv_no_header
python3 ./run_query.py bradlo-test $ENGINE sample_csv_no_header
python3 ./load_csv.py bradlo-test $ENGINE sample_alt_syntax.csv --delim="|" --quotechar="'" -r sample_csv_alt_syntax
python3 ./run_query.py bradlo-test $ENGINE sample_csv_alt_syntax

# load_json
python3 ./load_json.py bradlo-test $ENGINE sample.json -r sample_json
python3 ./run_query.py bradlo-test $ENGINE sample_json

