#!/bin/bash

set -ex

COMPUTE="2021-10-11-bradlo-xs"

#python3 ./list_users.py
#python3 ./get_user.py <username>

# create compute (409 if already exists)
python3 ./create_compute.py $COMPUTE --size=XS
python3 ./list_computes.py
python3 ./list_computes.py --state=PROVISIONED
python3 ./get_compute.py $COMPUTE

#python3 ./get_database.py sdk-test
# should return a 404

# create database
python3 ./create_database.py sdk-test $COMPUTE --overwrite
python3 ./list_databases.py
python3 ./get_database.py sdk-test

# show results, problems and errors
python3 ./run_query.py sdk-test $COMPUTE "1+1"
python3 ./show_results.py sdk-test $COMPUTE
python3 ./show_problems.py sdk-test $COMPUTE
python3 ./show_errors.py

# install source
python3 ./install_source.py sdk-test $COMPUTE hello.rel
python3 ./list_sources.py sdk-test $COMPUTE
python3 ./get_source.py sdk-test $COMPUTE hello
python3 ./list_edb.py sdk-test $COMPUTE

# clone database
python3 ./clone_database.py sdk-test-clone $COMPUTE sdk-test
python3 ./list_databases.py
python3 ./get_database.py sdk-test-clone
python3 ./list_sources.py sdk-test $COMPUTE
python3 ./get_source.py sdk-test $COMPUTE hello
python3 ./list_edb.py sdk-test $COMPUTE

# delete source
python3 ./list_sources.py sdk-test $COMPUTE
python3 ./delete_source.py sdk-test $COMPUTE hello
python3 ./list_sources.py sdk-test $COMPUTE
