name: Build

on:
  push:
  schedule:
    - cron: '30 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]
        #run: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/test
      with:
        client_id: ${{ secrets.CLIENT_ID }}
        client_secret: ${{ secrets.CLIENT_SECRET }}
        client_credentials_url: ${{ secrets.CLIENT_CREDENTIALS_URL }}

