name: Publish RelationalAI SDK Snowflake to PyPi

on: workflow_dispatch

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        working-directory: ./relationalai-sdk-snowflake
        run: python3 -m pip install --upgrade build && python3 -m build
      - name: Publish package to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: ./relationalai-sdk-snowflake/dist
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
